import { ISong } from "src/types/types";

export const songs: ISong[] = [
  {
    title: "Take me home, country roads",
    artist: "John Denver",
    start: 19,
    genre: "Country",
    youtubeWatchCode: "1vrEljMfXYo",
  },
  {
    title: "The Final Countdown",
    artist: "Europe",
    start: 103,
    genre: "Rock",
    youtubeWatchCode: "9jK-NcRmVcw",
  },
  {
    title: "Ordinary World",
    artist: "Duran Duran",
    start: 124,
    genre: "Rock",
    youtubeWatchCode: "FqIACCH20JU",
  },
  {
    title: "Runaway",
    artist: "Bon Jovi",
    start: 71,
    genre: "Rock",
    youtubeWatchCode: "s86K-p089R8",
  },
  {
    title: "Blinding Lights",
    artist: "The Weeknd",
    start: 129,
    genre: ["R&B/Soul", "Synthwave"],
    youtubeWatchCode: "fHI8X4OXluQ",
  },
  {
    title: "All by myself",
    artist: "Mace",
    start: 200,
    genre: "Pop",
    youtubeWatchCode: "1FB6g0uJxoo",
  },
  {
    title: "Take me home, country roads",
    artist: "Mace",
    start: 6 * 60,
    genre: "Country",
    youtubeWatchCode: "1FB6g0uJxoo",
  },
  {
    title: "Arsonist's Lullabye",
    artist: "Hozier",
    start: 60 + 15,
    genre: "Alternative/Indie",
    youtubeWatchCode: "QCMpHbYz9BE",
  },
  {
    title: "Space Oddity",
    artist: "David Bowie",
    start: 87,
    genre: "Rock",
    youtubeWatchCode: "iYYRH4apXDo",
  },
  {
    title: "Afrika",
    artist: "Viktor",
    start: 25,
    genre: "Pop",
    youtubeWatchCode: "mArsZJbfzYU",
  },
  {
    title: "Movie",
    artist: "Tom Misch",
    start: 106,
    genre: "R&B/Soul",
    youtubeWatchCode: "DUzEYcR2VtM",
  },
  {
    title: "Livin' On A Prayer",
    artist: "Bon Jovi",
    start: 86,
    genre: "Rock",
    youtubeWatchCode: "lDK9QqIzhwk",
  },
  {
    title: "Gyöngyhajú lány",
    artist: "Omega",
    start: 125,
    genre: "Pop",
    youtubeWatchCode: "bz3Yw3XbsVQ",
  },
  {
    title: "White Dove",
    artist: "Scorpions",
    start: 77,
    genre: "Rock",
    youtubeWatchCode: "SugjbOt0BqE",
  },
  {
    title: "Dívka S Perlami Ve Vlasech",
    artist: "Aleš Brichta",
    start: 80,
    genre: "Rock",
    youtubeWatchCode: "lP-R7hIBg0s",
  },
  {
    title: "Crawling",
    artist: "Linkin Park",
    start: 80,
    genre: "Alternative/Indie",
    youtubeWatchCode: "I6NU3kWqnDE",
  },
  {
    title: "Heavy",
    artist: "Linkin Park feat. Kiiara",
    start: 54,
    genre: ["Pop", "Pop Rock", "Contemporary R&B"],
    youtubeWatchCode: "uEITghr7Rxg",
  },
  {
    title: "Don't Look Back in Anger",
    artist: "Oasis",
    start: 127,
    genre: ["Rock", "Alternative/Indie"],
    youtubeWatchCode: "X59TlszGtfM",
  },
  {
    title: "Skinny Love",
    artist: "Birdy",
    start: 109,
    genre: ["Pop", "Alternative/Indie"],
    youtubeWatchCode: "FjpX3cA36G0",
  },
  {
    title: "The Hardest Part",
    artist: "Coldplay",
    start: 138,
    genre: ["Rock", "Alternative/Indie"],
    youtubeWatchCode: "yeGtvyHl9oY",
  },
  {
    title: "Bitter Sweet Symphony",
    artist: "The Verve",
    start: 220,
    genre: "Rock",
    youtubeWatchCode: "1WTATreAg08",
  },
  {
    title: "Wicked Game",
    artist: "Chris Isaak",
    start: 126,
    genre: ["Rock", "Pop"],
    youtubeWatchCode: "oadhHk2xs6c",
  },
  {
    title: "Our House",
    artist: "Madness",
    start: 55,
    genre: "Pop",
    youtubeWatchCode: "aRSueiSbcyA",
  },
  {
    title: "Kashmir",
    artist: "Led Zeppelin",
    start: 134,
    genre: ["Rock", "Pop", "Hip-Hop/Rap"],
    youtubeWatchCode: "SsaFBNvhce",
  },
  {
    title: "Barracuda",
    artist: "Heart",
    start: 129,
    genre: "Rock",
    youtubeWatchCode: "p6v6wWmEYvY",
  },
  {
    title: "Carry on Wayward Son",
    artist: "Kansas",
    start: 140,
    genre: ["Classic Rock", "Progressive/Art Rock"],
    youtubeWatchCode: "tz6u9suVNlY",
  },
  {
    title: "Bad Habits",
    artist: "Ed Sheeran",
    start: 93,
    genre: "Pop",
    youtubeWatchCode: "hJWSZDJb-W4",
  },
  // {
  //   title: "The End",
  //   artist: "The Doors",
  //   start: 124,
  //   genre: "Rock",
  //   youtubeWatchCode: "BXqPNlng6uI",
  // },
];
